# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import operations_list as op


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(521, 409)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(19, 9, 291, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.calculateButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.calculateButton.setObjectName("calculateButton")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.SpanningRole, self.calculateButton)
        self.labelSetB = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelSetB.setObjectName("labelSetB")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.labelSetB)
        self.lineEditSetA = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEditSetA.setObjectName("lineEditSetA")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.lineEditSetA)
        self.lineEditSetB = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEditSetB.setObjectName("lineEditSetB")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.lineEditSetB)
        self.labelSetA = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelSetA.setObjectName("labelSetA")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.labelSetA)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 129, 501, 272))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textUnion = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.textUnion.setEnabled(False)
        self.textUnion.setObjectName("textUnion")
        self.gridLayout.addWidget(self.textUnion, 0, 0, 1, 1)
        self.textDifer = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.textDifer.setEnabled(False)
        self.textDifer.setObjectName("textDifer")
        self.gridLayout.addWidget(self.textDifer, 0, 1, 1, 1)
        self.textInter = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.textInter.setEnabled(False)
        self.textInter.setObjectName("textInter")
        self.gridLayout.addWidget(self.textInter, 1, 0, 1, 1)
        self.textDifer_2 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.textDifer_2.setEnabled(False)
        self.textDifer_2.setObjectName("textDifer_2")
        self.gridLayout.addWidget(self.textDifer_2, 1, 1, 1, 1)
        self.textCart = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.textCart.setEnabled(False)
        self.textCart.setObjectName("textCart")
        self.gridLayout.addWidget(self.textCart, 2, 0, 1, 1)
        self.textMisc = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.textMisc.setEnabled(False)
        self.textMisc.setObjectName("textMisc")
        self.gridLayout.addWidget(self.textMisc, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.calculateButton.clicked.connect(
            self.handleClick)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def handleClick(self):
        A = self.lineEditSetA.text().split(",")
        B = self.lineEditSetB.text().split(",")
        union = op.Union(A, B)
        inter = op.Intersection(A, B)
        diff_1 = op.Difference(A, B)
        diff_2 = op.Difference(B, A)
        cart = op.Cartesian(A, B)
        equal = op.Equal(A, B)
        subset = op.Subset(A, B)
        msg1 = "A and B are equals" if equal else "A and B are not equals"
        msg2 = "A are a subset of B" if equal else "A arent a subset of B"

        self.textUnion.setPlainText(','.join(str(e) for e in union))
        self.textInter.setPlainText(','.join(str(e) for e in inter))
        self.textDifer.setPlainText(','.join(str(e) for e in diff_1))
        self.textDifer_2.setPlainText(','.join(str(e) for e in diff_2))
        self.textCart.setPlainText(','.join(str(e) for e in cart))
        self.textMisc.setPlainText(f"{msg1}\n{msg2}")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.calculateButton.setText(_translate("MainWindow", "Calculate"))
        self.labelSetB.setText(_translate("MainWindow", "Set B"))
        self.labelSetA.setText(_translate("MainWindow", "Set A"))
        self.textUnion.setPlainText(_translate("MainWindow", "Union"))
        self.textDifer.setPlainText(
            _translate("MainWindow", "Diferencia A - B"))
        self.textInter.setPlainText(_translate("MainWindow", "Interseccion"))
        self.textDifer_2.setPlainText(
            _translate("MainWindow", "Diferencia B - A"))
        self.textCart.setPlainText(_translate(
            "MainWindow", "Producto Cartesiano"))
        self.textMisc.setPlainText(_translate("MainWindow", "Misc"))
