# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import operations_list as op


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(521, 409)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(19, 9, 291, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.calculateButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.calculateButton.setObjectName("calculateButton")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.SpanningRole, self.calculateButton)
        self.labelSetB = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelSetB.setObjectName("labelSetB")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.labelSetB)
        self.lineEditSetA = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEditSetA.setObjectName("lineEditSetA")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.lineEditSetA)
        self.lineEditSetB = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEditSetB.setObjectName("lineEditSetB")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.lineEditSetB)
        self.labelSetA = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelSetA.setObjectName("labelSetA")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.labelSetA)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 129, 501, 272))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textUnion = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.textUnion.setEnabled(True)
        self.textUnion.setObjectName("textUnion")
        self.gridLayout.addWidget(self.textUnion, 0, 0, 2, 1)
        self.textDifer = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.textDifer.setEnabled(True)
        self.textDifer.setObjectName("textDifer")
        self.gridLayout.addWidget(self.textDifer, 0, 1, 2, 1)
        self.textInter = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.textInter.setEnabled(True)
        self.textInter.setObjectName("textInter")
        self.gridLayout.addWidget(self.textInter, 2, 0, 2, 1)
        self.textDifer_2 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.textDifer_2.setEnabled(True)
        self.textDifer_2.setObjectName("textDifer_2")
        self.gridLayout.addWidget(self.textDifer_2, 2, 1, 2, 1)
        self.textCart = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.textCart.setEnabled(True)
        self.textCart.setObjectName("textCart")
        self.gridLayout.addWidget(self.textCart, 4, 0, 2, 2)
        self.textMisc = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.textMisc.setEnabled(True)
        self.textMisc.setObjectName("textMisc")
        self.gridLayout.addWidget(self.textMisc, 6, 0, 2, 1)
        self.textUniversal = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.textUniversal.setEnabled(True)
        self.textUniversal.setObjectName("textUniversal")
        self.gridLayout.addWidget(self.textUniversal, 6, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.calculateButton.clicked.connect(
            self.handleClick)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def handleClick(self):
        A = self.lineEditSetA.text().split(",")
        B = self.lineEditSetB.text().split(",")
        U = op.removeElements(A + B)
        union = op.Union(A, B)
        inter = op.Intersection(A, B)
        diff_1 = op.Difference(A, B)
        diff_2 = op.Difference(B, A)
        cart = op.Cartesian(A, B)
        equal = op.Equal(A, B)
        subset = op.Subset(A, B)
        msg1 = "A y B son iguales" if equal else "A y B no son iguales"
        msg2 = "B es un subconjunto A" if subset else "B no es un subconjunto de B"

        self.textUnion.setPlainText(','.join(str(e) for e in union))
        self.textInter.setPlainText(','.join(str(e) for e in inter))
        self.textDifer.setPlainText(','.join(str(e) for e in diff_1))
        self.textDifer_2.setPlainText(','.join(str(e) for e in diff_2))
        self.textCart.setPlainText(','.join(str(e) for e in cart))
        self.textMisc.setPlainText(f"{msg1}\n{msg2}")
        self.textUniversal.setPlainText(','.join(str(e) for e in U))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Teoria de conjuntos"))
        self.calculateButton.setText(_translate("MainWindow", "Calcular"))
        self.labelSetB.setText(_translate("MainWindow", "Conjunto B"))
        self.labelSetA.setText(_translate("MainWindow", "Conjunto A"))
        self.textUnion.setPlainText(_translate("MainWindow", "Union"))
        self.textDifer.setPlainText(
            _translate("MainWindow", "Diferencia A - B"))
        self.textInter.setPlainText(_translate("MainWindow", "Interseccion"))
        self.textDifer_2.setPlainText(
            _translate("MainWindow", "Diferencia B - A"))
        self.textCart.setPlainText(_translate(
            "MainWindow", "Producto Cartesiano"))
        self.textMisc.setPlainText(_translate("MainWindow", "Propocisiones"))
        self.textUniversal.setPlainText(
            _translate("MainWindow", "Conjunto Universal"))
